controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    chassis_controller:
      type: swerve_gazebo_sim/ChassisController
joint_state_broadcaster:
  ros__parameters: {}
