controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    steering_controller:
      type: forward_command_controller/ForwardCommandController
    wheel_controller:
      type: forward_command_controller/ForwardCommandController
joint_state_broadcaster:
  ros__parameters: {}
